defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"

[traefikLog]
  filePath = "/logs/traefik.log"

[accessLog]
  filePath = "/logs/access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[certificatesResolvers.mixnjuice.acme]
email = "support@mixnjuice.com"
storage = "/certs/acme.json"
entryPoint = "https"
onHostRule = true
  [certificatesResolvers.mixnjuice.acme.httpChallenge]
  entryPoint = "http"
